name: Chapter 09 - Sauce Labs Integration

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Tests
      run: |
        cd ./solutions/chapter_09/saucelabs
        npm install
        npm run test:sauce
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
    - uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: |
          ./solutions/chapter_09/saucelabs/logs
          ./solutions/chapter_09/saucelabs/myAllureReport
      if: always()
